2024-11-08 05:51:36,535 INFO    MainThread:158381 [wandb_setup.py:_flush():79] Current SDK version is 0.18.6
2024-11-08 05:51:36,535 INFO    MainThread:158381 [wandb_setup.py:_flush():79] Configure stats pid to 158381
2024-11-08 05:51:36,535 INFO    MainThread:158381 [wandb_setup.py:_flush():79] Loading settings from /home/codespace/.config/wandb/settings
2024-11-08 05:51:36,535 INFO    MainThread:158381 [wandb_setup.py:_flush():79] Loading settings from /workspaces/aitask/notebooks/wandb/settings
2024-11-08 05:51:36,535 INFO    MainThread:158381 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-11-08 05:51:36,535 INFO    MainThread:158381 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-11-08 05:51:36,535 INFO    MainThread:158381 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-11-08 05:51:36,535 INFO    MainThread:158381 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-08 05:51:36,535 INFO    MainThread:158381 [wandb_init.py:_log_setup():533] Logging user logs to /workspaces/aitask/notebooks/wandb/run-20241108_055136-pvbm62et/logs/debug.log
2024-11-08 05:51:36,535 INFO    MainThread:158381 [wandb_init.py:_log_setup():534] Logging internal logs to /workspaces/aitask/notebooks/wandb/run-20241108_055136-pvbm62et/logs/debug-internal.log
2024-11-08 05:51:36,535 INFO    MainThread:158381 [wandb_init.py:init():619] calling init triggers
2024-11-08 05:51:36,535 INFO    MainThread:158381 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'architecture': 'ResNet50', 'dataset': 'TrashNet', 'epochs': 10}
2024-11-08 05:51:36,535 INFO    MainThread:158381 [wandb_init.py:init():669] starting backend
2024-11-08 05:51:36,535 INFO    MainThread:158381 [wandb_init.py:init():673] sending inform_init request
2024-11-08 05:51:36,538 INFO    MainThread:158381 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-11-08 05:51:36,539 INFO    MainThread:158381 [wandb_init.py:init():686] backend started and connected
2024-11-08 05:51:36,549 INFO    MainThread:158381 [wandb_run.py:_label_probe_notebook():1341] probe notebook
2024-11-08 05:51:36,550 INFO    MainThread:158381 [wandb_init.py:init():781] updated telemetry
2024-11-08 05:51:36,558 INFO    MainThread:158381 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-11-08 05:53:06,574 ERROR   MainThread:158381 [wandb_init.py:init():841] encountered error: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2024-11-08 05:53:06,574 ERROR   MainThread:158381 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/codespace/.python/current/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 847, in init
    raise error
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2024-11-08 06:02:45,471 INFO    MainThread:158381 [wandb_settings.py:_apply_login():1971] Applying login settings: {}
2024-11-08 06:02:45,479 INFO    MainThread:158381 [wandb_setup.py:_flush():79] Current SDK version is 0.18.6
2024-11-08 06:02:45,479 INFO    MainThread:158381 [wandb_setup.py:_flush():79] Configure stats pid to 158381
2024-11-08 06:02:45,480 INFO    MainThread:158381 [wandb_setup.py:_flush():79] Loading settings from /home/codespace/.config/wandb/settings
2024-11-08 06:02:45,480 INFO    MainThread:158381 [wandb_setup.py:_flush():79] Loading settings from /workspaces/aitask/notebooks/wandb/settings
2024-11-08 06:02:45,480 INFO    MainThread:158381 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-11-08 06:02:45,480 INFO    MainThread:158381 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-11-08 06:02:45,480 INFO    MainThread:158381 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-11-08 06:02:45,480 INFO    MainThread:158381 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-08 06:02:45,481 INFO    MainThread:158381 [wandb_init.py:_log_setup():533] Logging user logs to /workspaces/aitask/notebooks/wandb/run-20241108_060245-2yjsj684/logs/debug.log
2024-11-08 06:02:45,481 INFO    MainThread:158381 [wandb_init.py:_log_setup():534] Logging internal logs to /workspaces/aitask/notebooks/wandb/run-20241108_060245-2yjsj684/logs/debug-internal.log
2024-11-08 06:02:45,481 INFO    MainThread:158381 [wandb_init.py:init():619] calling init triggers
2024-11-08 06:02:45,481 INFO    MainThread:158381 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'architecture': 'ResNet50', 'dataset': 'TrashNet', 'epochs': 10}
2024-11-08 06:02:45,481 INFO    MainThread:158381 [wandb_init.py:init():669] starting backend
2024-11-08 06:02:45,482 INFO    MainThread:158381 [wandb_init.py:init():673] sending inform_init request
2024-11-08 06:02:45,488 INFO    MainThread:158381 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-11-08 06:02:45,494 INFO    MainThread:158381 [wandb_init.py:init():686] backend started and connected
2024-11-08 06:02:45,505 INFO    MainThread:158381 [wandb_run.py:_label_probe_notebook():1341] probe notebook
2024-11-08 06:02:45,506 INFO    MainThread:158381 [wandb_init.py:init():781] updated telemetry
2024-11-08 06:02:45,512 INFO    MainThread:158381 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-11-08 06:02:45,883 ERROR   MainThread:158381 [wandb_init.py:init():841] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-11-08 06:02:45,884 ERROR   MainThread:158381 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/codespace/.python/current/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 847, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
